<?php
require_once 'includes/config.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= SITE_NAME ?> — Powered by MSEndpoint</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <a href="#" class="logo">
                <span class="logo-icon">⚡</span>
                <span class="logo-text"><?= SITE_NAME ?></span>
            </a>
            <div class="nav-links">
                <a href="#features">Features</a>
                <a href="#pricing">Pricing</a>
                <a href="<?= STRIPE_URL ?>" class="btn-primary">Get Started</a>
            </div>
        </div>
    </nav>

    <header class="hero">
        <div class="container">
            <div class="hero-content">
                <span class="badge">SaaS Tool by MSEndpoint</span>
                <h1><?= HERO_TITLE ?></h1>
                <p><?= HERO_SUBTITLE ?></p>
                <div class="hero-actions">
                    <a href="<?= STRIPE_URL ?>" class="btn-primary btn-lg">Start Building Now</a>
                    <a href="#features" class="btn-outline btn-lg">Explore Features</a>
                </div>
            </div>
        </div>
        <div class="hero-visual"></div>
    </header>

    <section id="features" class="features">
        <div class="container">
            <div class="section-header">
                <h2>Why Choose <?= SITE_NAME ?>?</h2>
                <p>Designed for performance, security, and scalability.</p>
            </div>
            <div class="features-grid">
                <!-- AI will populate this -->
                <div class="feature-card">
                    <div class="icon">🚀</div>
                    <h3>Fast Performance</h3>
                    <p>Built with efficiency in mind to help you work faster than ever.</p>
                </div>
                <div class="feature-card">
                    <div class="icon">🔒</div>
                    <h3>Secure by Design</h3>
                    <p>Your data is protected with industry-standard security practices.</p>
                </div>
                <div class="feature-card">
                    <div class="icon">☁️</div>
                    <h3>Cloud Ready</h3>
                    <p>Deploy anywhere, anytime with our cloud-optimized architecture.</p>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer">
        <div class="container">
            <div class="footer-grid">
                <div class="footer-brand">
                    <div class="logo">
                        <span class="logo-icon">⚡</span>
                        <span class="logo-text"><?= SITE_NAME ?></span>
                    </div>
                    <p>A premium SaaS tool generated by the MSEndpoint SaaS Factory.</p>
                </div>
                <div class="footer-links">
                    <h4>Product</h4>
                    <a href="#">Features</a>
                    <a href="#">Pricing</a>
                </div>
                <div class="footer-links">
                    <h4>Company</h4>
                    <a href="https://msendpoint.com">MSEndpoint</a>
                    <a href="https://github.com/Msendpoint">GitHub</a>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; <?= date('Y') ?> <?= SITE_NAME ?>. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>
